### ISSUE TITLE
linux_distribution deprecated

### ISSUE THREAD

**Issue by DonRichie** [whois-api-llc/python-simple-geoip#1]
Hello Sir,

```
File "/usr/lib/python3.8/site-packages/simple_geoip/settings.py", line 9, in <module>
    from platform import mac_ver, win32_ver, linux_distribution, system

ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)
```

The internet says linux_distribution is deprecated. I am using Python 3.8 and run into the error above.
I kindly request a fix of this issue.

**Comment by whoisxmlapi** [comment]
The issue has been fixed, we have eliminated the use of the deprecated command.
