### ISSUE TITLE
simple-geoip refuse imediately

### ISSUE THREAD

**Issue by theduckchannel** [whois-api-llc/python-simple-geoip#2]
Hi,

i wrote the following code

`from simple_geoip import GeoIP

geoip = GeoIP("I put my api key here");

data = geoip.lookup("8.8.8.8")
print(data)`

and i get this error:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from simple_geoip import GeoIP
  File "/home/fredlins/.local/lib/python3.8/site-packages/simple_geoip/__init__.py", line 16, in <module>
    from .geoip import GeoIP
  File "/home/fredlins/.local/lib/python3.8/site-packages/simple_geoip/geoip.py", line 14, in <module>
    from .settings import API_URI, MAX_RETRIES, USER_AGENT
  File "/home/fredlins/.local/lib/python3.8/site-packages/simple_geoip/settings.py", line 9, in <module>
    from platform import mac_ver, win32_ver, linux_distribution, system
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)

Remember the code sample in README.md is wrong and with mistakes.

**Comment by whoisxmlapi** [comment]
Hi Fred,

We'd be happy to assist you with your Inquiry. I've attached our Technical
Support Team <service.desk@whoisxmlapi.com> to provide a direct response
and get this sorted out as soon as possible. @Whoisxmlapi Support
<service.desk@whoisxmlapi.com>

Please let us know if any additional information comes to light that we may
assist with.

     Thanks,

*Steven Seagondollar*
*Operations Support Specialist*
__________________________________________

*Direct Email - steven@whoisxmlapi.com <steven@whoisxmlapi.com>*
*Direct Line - 1-323-792-7296 EXT.710*
*_____________________________________*


*WhoisXML API Products & Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1Gy7zkW1GGmmy3XT__30&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*WhoisXML API Contact & Support
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51Lw3rjF4fDX92W2TX1&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*WhoisXML API Mailing Address
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3P4Gj23P3jgXW3zfQ5y3C2GWxW3NX4pL2FW0Vvn4fLNcH123&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*_____________________________________*

*Enterprise API Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1Gy7zkW1GGmmy3XT__30&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*Enterprise Data Feed Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1GzmHjW3yLW9L3K2Vj4F3z8nfmW1v71&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*Enterprise Security Intelligence Packages
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPdSD1CW7fZnGx3LqYtzV1S-nd2-2kyg103?te=W3R5hFj4cm2zwW3_R5941JHRQyW3T3r0N3ZSzg_W1JxwY51LvdzJW1GGmmy3XT__3W4cgz5M4fGCnCW49M9mh1GHD7pW4hLygn4r51p_F3Z_W6yW2gZ1&si=8000000000352168&pi=2da8be3a-ae1e-4d2a-fd78-9edd5a0d71ed>*
*_____________________________________*

**Comment by whoisxmlapi** [comment]
Dear Fred,

thank you for pointing this out. The issue has been fixed now; with the current github version your code should work.

WhoisXML API support
